url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Alejandro Dinamarca" # the name of your site, e.g. ACME Corp.
email: "alejandro.dinamarca.u@gmail.com"

personal:
  name: "Alejandro Dinamarca"
  email: "alejandro.dinamarca.u@gmail.com"
  phone: "12345"
  github: "dinalejo"
